# Generated by Django 3.2.9 on 2022-01-12 03:40

from django.db import migrations, models

from racket.models import Racket


def gen_master(apps, schema_editor):
    Racket(name="블레이드 98 덴스", weight=305, pattern="18 : 20", headsize=98, length=27, balance=320, regDateInt=2021,
           manufacturer="WILSON").save()
    Racket(name="퓨어 드라이브", weight=300, pattern="16 : 19", headsize=100, length=27, balance=330, regDateInt=2019,
           manufacturer="BABOLAT").save()
    Racket(name="퓨어 에어로", weight=300, pattern="16 : 19", headsize=100, length=27, balance=330, regDateInt=2019,
           manufacturer="BABOLAT").save()
    Racket(name="스피드 프로", weight=310, pattern="18 : 20", headsize=100, length=27, balance=310, regDateInt=2020,
           manufacturer="HEAD").save()
    Racket(name="프레스티지 프로", weight=320, pattern="18 : 20", headsize=98, length=27, balance=310, regDateInt=2021,
           manufacturer="HEAD").save()
    Racket(name="그래비티 투어", weight=315, pattern="18 : 20", headsize=100, length=27, balance=310, regDateInt=2021,
           manufacturer="HEAD").save()
    Racket(name="프로스태프 97 RF", weight=340, pattern="16 : 19", headsize=97, length=27, balance=305, regDateInt=2021,
           manufacturer="WILSON").save()
    Racket(name="라디칼 프로", weight=315, pattern="16 : 19", headsize=98, length=27, balance=315, regDateInt=2020,
           manufacturer="HEAD").save()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Racket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='라켓이름')),
                ('weight', models.IntegerField(default=0, verbose_name='라켓무게')),
                ('pattern', models.CharField(max_length=20, verbose_name='라켓스트링패턴')),
                ('headsize', models.IntegerField(default=0, verbose_name='라켓헤드사이즈')),
                ('length', models.FloatField(default=0, verbose_name='라켓길이')),
                ('balance', models.IntegerField(default=0, verbose_name='라켓밸런스')),
                ('regDateInt', models.IntegerField(default=0, verbose_name='라켓생산년도')),
                ('hitCount', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('manufacturer', models.CharField(default='등록전', max_length=20, verbose_name='제조사')),
            ],
        ),
        migrations.RunPython(gen_master)

    ]
