# Generated by Django 3.2.9 on 2022-01-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminReview', models.TextField(verbose_name='운영자리뷰')),
                ('adminPower', models.FloatField(default=0, verbose_name='운영자파워평점')),
                ('adminSpin', models.FloatField(default=0, verbose_name='운영자스핀평점')),
                ('adminManeuverability', models.FloatField(default=0, verbose_name='운영자조작성평점')),
                ('adminStability', models.FloatField(default=0, verbose_name='운영자면안정성평점')),
                ('adminComfort', models.FloatField(default=0, verbose_name='운영자안락함평점')),
            ],
        ),
    ]
