# Generated by Django 3.2.9 on 2022-03-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racket',
            name='k_name',
            field=models.CharField(default=0, max_length=100, verbose_name='한국형이름'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='racketbrand',
            name='k_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='racket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='racketbrand',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='racketdetail',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
