# Generated by Django 3.2.9 on 2022-01-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racket', '0002_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racketdetail',
            name='racket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='racket.racket'),
        ),
    ]
