# Generated by Django 3.2.9 on 2022-02-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racket', '0002_auto_20220204_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='racket',
            name='countLike',
            field=models.IntegerField(default=0, verbose_name='좋아요개수'),
        ),
    ]
