# Generated by Django 3.2.9 on 2022-01-25 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racket', '0004_alter_racketdetail_racket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racketdetail',
            name='racket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='racket.racket'),
        ),
    ]
