# Generated by Django 3.2.9 on 2022-01-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racket', '0005_alter_racketdetail_racket'),
    ]

    operations = [
        migrations.AddField(
            model_name='racket',
            name='visitorReviewScore',
            field=models.FloatField(default=0, verbose_name='고객들의리뷰평균'),
        ),
    ]
