# Generated by Django 3.2.9 on 2022-01-25 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racket', '0006_racket_visitorreviewscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racket',
            name='visitorReviewScore',
        ),
    ]
