import time

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

# Create your models here.
from django.db.models import Avg

from account.models import User

class RacketBrand(models.Model):
    name = models.CharField(max_length=20)
    k_name = models.CharField(max_length=20)


class Racket(models.Model):
    name = models.CharField('라켓이름', max_length=100)
    k_name = models.CharField('한국형이름', max_length=100)
    weight = models.IntegerField('라켓무게', default=0)
    pattern = models.CharField('라켓스트링패턴', max_length=100)
    headsize = models.IntegerField('라켓헤드사이즈', default=0)
    length = models.FloatField('라켓길이', default=0)
    balance = models.CharField('라켓밸런스', max_length=20, default=0)
    stiffness = models.IntegerField('라켓강성', default=0)
    brand = models.ForeignKey(RacketBrand, on_delete=models.CASCADE)
    like = models.ManyToManyField(User, related_name='like')
    visitorAvgScore = models.FloatField('사용자평점평균', default=0)
    countLike = models.IntegerField('좋아요개수', default=0)

    # def countLikeSave(self):
    #     getCount = Racket.values('created', 'name').annotate(product_cnt=Count('name'))
    #
    # self.visitorreview_set.aggregate(Avg('visitorScore'))['visitorScore__avg']

    def thumb_img_url(self):
        img_names = {
            'Aero 112': 'Aero 112',
            'AeroPro Drive': 'AeroPro Drive',
            'AeroPro Drive Plus': 'AeroPro Drive Plus',
            'AeroPro Lite': 'AeroPro Lite',
            'AeroPro Team': 'AeroPro Team',
            'Astrel 100': 'Astrel 100',
            'Astrel 105': 'Astrel 105',
            'Astrel 115': 'Astrel 115',
            'ATP TFight 280 XTC': 'ATP TFight 280 XTC',
            'ATP TFight 295 XTC': 'ATP TFight 295 XTC',
            'ATP TFight 300 XTC': 'ATP TFight 300 XTC',
            'ATP TFight 305 XTC': 'ATP TFight 305 XTC',
            'ATP TFight 315 XTC': 'ATP TFight 315 XTC',
            'ATP TFight 320 XTC': 'ATP TFight 320 XTC',
            'BioFibre F3.1 Tour': 'BioFibre F3.1 Tour',
            'BioFibre M2.1': 'BioFibre M2.1',
            'BioFibre M3.1': 'BioFibre M3.1',
            'BioFibre S8.1 Lite': 'BioFibre S8.1 Lite',
            'Biomimetic 400': 'Biomimetic 400',
            'Biomimetic 400 Lite': 'Biomimetic 400 Lite',
            'Biomimetic 400 Tour': 'Biomimetic 400 Tour',
            'Biomimetic F2.0 Tour': 'Biomimetic F2.0 Tour',
            'Biomimetic F3.0 Tour': 'Biomimetic F3.0 Tour',
            'Biomimetic F4.0 Tour': 'Biomimetic F4.0 Tour',
            'Biomimetic F5.0 Tour': 'Biomimetic F5.0 Tour',
            'Biomimetic M2.0': 'Biomimetic M2.0',
            'Biomimetic M3.0': 'Biomimetic M3.0',
            'Biomimetic M4.0': 'Biomimetic M4.0',
            'Biomimetic M5.0': 'Biomimetic M5.0',
            'Biomimetic M6.0': 'Biomimetic M6.0',
            'Biomimetic S 2.0 Lite': 'Biomimetic S 2.0 Lite',
            'Biomimetic S 7.0 Lite': 'Biomimetic S 7.0 Lite',
            'Biomimetic S2.0 Lite': 'Biomimetic S2.0 Lite',
            'Biomimetic S3.0 Lite': 'Biomimetic S3.0 Lite',
            'Biomimetic S4.0 Lite': 'Biomimetic S4.0 Lite',
            'Biomimetic S5.0 Lite': 'Biomimetic S5.0 Lite',
            'Biomimetic S6.0 Lite': 'Biomimetic S6.0 Lite',
            'Biomimetic S7.0 Lite': 'Biomimetic S7.0 Lite',
            'Biomimetic S8.0 Lite': 'Biomimetic S8.0 Lite',
            'Black Ace (300)': 'Black Ace (300)',
            'Black Ace (315)': 'Black Ace (315)',
            'Black Ace 98': 'Black Ace 98',
            'Blade 100L v7': 'Blade 100L v7',
            'Blade 104': 'Blade 104',
            'Blade 104 v7': 'Blade 104 v7',
            'Blade 93': 'Blade 93',
            'Blade 98 (16x19)': 'Blade 98 (16x19)',
            'Blade 98 (16x19) Countervail': 'Blade 98 (16x19) Countervail',
            'Blade 98 (16x19) v7': 'Blade 98 (16x19) v7',
            'Blade 98 (18x20)': 'Blade 98 (18x20)',
            'Blade 98 (18x20) Countervail': 'Blade 98 (18x20) Countervail',
            'Blade 98 (18x20) v7': 'Blade 98 (18x20) v7',
            'Blade 98L (16x19)': 'Blade 98L (16x19)',
            'Blade 98S': 'Blade 98S',
            'Blade 98S (18x16) Countervail': 'Blade 98S (18x16) Countervail',
            'Blade 98S Spin (18x16)': 'Blade 98S Spin (18x16)',
            'Blade SW104 Autograph Countervail': 'Blade SW104 Autograph Countervail',
            'Blade SW104 Autograph v7': 'Blade SW104 Autograph v7',
            'Boost Aero': 'Boost Aero',
            'Boost Drive': 'Boost Drive',
            'Boost Strike': 'Boost Strike',
            'Bryan Bros Ltd. Edition 95': 'Bryan Bros Ltd. Edition 95',
            'Burn 100': 'Burn 100',
            'Burn 100 Countervail': 'Burn 100 Countervail',
            'Burn 100 LS': 'Burn 100 LS',
            'Burn 100 Team': 'Burn 100 Team',
            'Burn 100 ULS': 'Burn 100 ULS',
            'Burn 100S': 'Burn 100S',
            'Burn 100S Countervail': 'Burn 100S Countervail',
            'Burn 95': 'Burn 95',
            'Burn 95 Countervail': 'Burn 95 Countervail',
            'Burn FST 95': 'Burn FST 95',
            'Burn FST 99': 'Burn FST 99',
            'Burn FST 99S': 'Burn FST 99S',
            'BX2 Fast Pro 100': 'BX2 Fast Pro 100',
            'BX2 Force Comp': 'BX2 Force Comp',
            'BX2 X Fast LT': 'BX2 X Fast LT',
            'BX2 X Feel Pro 95': 'BX2 X Feel Pro 95',
            'BX2 X Feel Tour': 'BX2 X Feel Tour',
            'BX2 X Force 98': 'BX2 X Force 98',
            'BX2 X Force Lite': 'BX2 X Force Lite',
            'BX2 X Force Pro': 'BX2 X Force Pro',
            'C10 Pro Matte Finish': 'C10 Pro Matte Finish',
            'Chrome 100 300g': 'Chrome 100 300g',
            'Clash': 'Clash',
            'Clash 100': 'Clash 100',
            'Clash 100 Tour': 'Clash 100 Tour',
            'Clash 100L': 'Clash 100L',
            'Clash 100UL': 'Clash 100UL',
            'Clash 108': 'Clash 108',
            'Clash 98': 'Clash 98',
            'Clash Tour': 'Clash Tour',
            'Classic Graphite 100': 'Classic Graphite 100',
            'Classic Graphite 100 Longbody': 'Classic Graphite 100 Longbody',
            'Classic Graphite 107': 'Classic Graphite 107',
            'Classic Response 97': 'Classic Response 97',
            'Classic Response 97': 'Classic Response 97',
            'Classic V1': 'Classic V1',
            'Classic V1 DE': 'Classic V1 DE',
            'CTS Synergy DB26': 'CTS Synergy DB26',
            'CX 200': 'CX 200',
            'CX 200 LS': 'CX 200 LS',
            'CX 200 OS': 'CX 200 OS',
            'CX 200 Tour 16x19': 'CX 200 Tour 16x19',
            'CX 200 Tour 18x20': 'CX 200 Tour 18x20',
            'CX 200+': 'CX 200+',
            'CX 400 Tour': 'CX 400 Tour',
            'CX Elite 260': 'CX Elite 260',
            'CX Pro 255': 'CX Pro 255',
            'CX Team 265': 'CX Team 265',
            'Drive 115': 'Drive 115',
            'Drive Lite': 'Drive Lite',
            'Drive Max 105': 'Drive Max 105',
            'Drive Max 110': 'Drive Max 110',
            'Envy 100 L': 'Envy 100 L',
            'Envy 110 UL': 'Envy 110 UL',
            'EZONE 100': 'EZONE 100',
            'EZONE 100 (285g)': 'EZONE 100 (285g)',
            'EZONE 100 (300g)': 'EZONE 100 (300g)',
            'EZONE 100 (300g) Blue': 'EZONE 100 (300g) Blue',
            'EZONE 100+': 'EZONE 100+',
            'EZONE 100+ (300g) Blue': 'EZONE 100+ (300g) Blue',
            'EZONE 100L': 'EZONE 100L',
            'EZONE 108': 'EZONE 108',
            'EZONE 98': 'EZONE 98',
            'EZONE 98 (285g)': 'EZONE 98 (285g)',
            'EZONE 98 (305g)': 'EZONE 98 (305g)',
            'EZONE 98 Tour': 'EZONE 98 Tour',
            'EZONE 98+': 'EZONE 98+',
            'EZONE Ai 100': 'EZONE Ai 100',
            'EZONE Ai 108': 'EZONE Ai 108',
            'EZONE Ai 98': 'EZONE Ai 98',
            'EZONE Ai 98 Lite': 'EZONE Ai 98 Lite',
            'EZONE Ai Feel': 'EZONE Ai Feel',
            'EZONE Ai Lite': 'EZONE Ai Lite',
            'EZONE DR 100': 'EZONE DR 100',
            'EZONE DR 100 (285g)': 'EZONE DR 100 (285g)',
            'EZONE DR 100 (300g)': 'EZONE DR 100 (300g)',
            'EZONE DR 98': 'EZONE DR 98',
            'EZONE DR 98 (310g)': 'EZONE DR 98 (310g)',
            'EZONE DR 98 Blue': 'EZONE DR 98 Blue',
            'EZONE DR Feel': 'EZONE DR Feel',
            'EZONE DR Rally': 'EZONE DR Rally',
            'EZONE Lite': 'EZONE Lite',
            'EZONE Xi 100': 'EZONE Xi 100',
            'EZONE Xi 107': 'EZONE Xi 107',
            'EZONE Xi 115': 'EZONE Xi 115',
            'EZONE Xi 98': 'EZONE Xi 98',
            'EZONE Xi Lite': 'EZONE Xi Lite',
            'Flow 105': 'Flow 105',
            'Flow Lite': 'Flow Lite',
            'Flow Tour': 'Flow Tour',
            'Force 100': 'Force 100',
            'Force 100 Tour': 'Force 100 Tour',
            'Force 105': 'Force 105',
            'Force 98': 'Force 98',
            'Force 98 Tour': 'Force 98 Tour',
            'Formula 100': 'Formula 100',
            'Formula Lite 100': 'Formula Lite 100',
            'Four BLX': 'Four BLX',
            'FX 500': 'FX 500',
            'FX 500 Lite': 'FX 500 Lite',
            'FX 500 LS': 'FX 500 LS',
            'FX 500 Tour': 'FX 500 Tour',
            'FX 700': 'FX 700',
            'Graphene 360 Extreme Lite': 'Graphene 360 Extreme Lite',
            'Graphene 360 Extreme MP': 'Graphene 360 Extreme MP',
            'Graphene 360 Extreme Pro': 'Graphene 360 Extreme Pro',
            'Graphene 360 Instinct Lite': 'Graphene 360 Instinct Lite',
            'Graphene 360 Instinct MP': 'Graphene 360 Instinct MP',
            'Graphene 360 Instinct PWR': 'Graphene 360 Instinct PWR',
            'Graphene 360 Instinct S': 'Graphene 360 Instinct S',
            'Graphene 360 Radical MP': 'Graphene 360 Radical MP',
            'Graphene 360 Radical Pro': 'Graphene 360 Radical Pro',
            'Graphene 360 Radical PWR': 'Graphene 360 Radical PWR',
            'Graphene 360 Radical S': 'Graphene 360 Radical S',
            'Graphene 360 Speed Lite': 'Graphene 360 Speed Lite',
            'Graphene 360 Speed MP': 'Graphene 360 Speed MP',
            'Graphene 360 Speed MP Lite': 'Graphene 360 Speed MP Lite',
            'Graphene 360 Speed Pro': 'Graphene 360 Speed Pro',
            'Graphene 360 Speed S': 'Graphene 360 Speed S',
            'Graphene 360+ Extreme Lite': 'Graphene 360+ Extreme Lite',
            'Graphene 360+ Extreme MP': 'Graphene 360+ Extreme MP',
            'Graphene 360+ Extreme PWR': 'Graphene 360+ Extreme PWR',
            'Graphene 360+ Extreme S': 'Graphene 360+ Extreme S',
            'Graphene 360+ Extreme Tour': 'Graphene 360+ Extreme Tour',
            'Graphene 360+ Gravity Lite': 'Graphene 360+ Gravity Lite',
            'Graphene 360+ Gravity MP': 'Graphene 360+ Gravity MP',
            'Graphene 360+ Gravity MP Lite': 'Graphene 360+ Gravity MP Lite',
            'Graphene 360+ Gravity Pro': 'Graphene 360+ Gravity Pro',
            'Graphene 360+ Gravity S': 'Graphene 360+ Gravity S',
            'Graphene 360+ Gravity Tour': 'Graphene 360+ Gravity Tour',
            'Graphene 360+ Instinct Lite': 'Graphene 360+ Instinct Lite',
            'Graphene 360+ Instinct MP': 'Graphene 360+ Instinct MP',
            'Graphene 360+ Instinct PWR': 'Graphene 360+ Instinct PWR',
            'Graphene 360+ Prestige Mid': 'Graphene 360+ Prestige Mid',
            'Graphene 360+ Prestige Midplus': 'Graphene 360+ Prestige Midplus',
            'Graphene 360+ Prestige Pro': 'Graphene 360+ Prestige Pro',
            'Graphene 360+ Prestige Tour': 'Graphene 360+ Prestige Tour',
            'Graphene 360+ Speed Lite': 'Graphene 360+ Speed Lite',
            'Graphene 360+ Speed MP': 'Graphene 360+ Speed MP',
            'Graphene 360+ Speed MP Lite': 'Graphene 360+ Speed MP Lite',
            'Graphene 360+ Speed Pro': 'Graphene 360+ Speed Pro',
            'Graphene 360+ Speed Pro (Black) R': 'Graphene 360+ Speed Pro (Black) R',
            'Graphene 360+ Speed PWR': 'Graphene 360+ Speed PWR',
            'Graphene 360+ Speed S': 'Graphene 360+ Speed S',
            'Graphene Extreme Lite': 'Graphene Extreme Lite',
            'Graphene Extreme MP': 'Graphene Extreme MP',
            'Graphene Extreme Pro': 'Graphene Extreme Pro',
            'Graphene Instinct MP': 'Graphene Instinct MP',
            'Graphene Instinct PWR': 'Graphene Instinct PWR',
            'Graphene Instinct Rev': 'Graphene Instinct Rev',
            'Graphene Instinct S': 'Graphene Instinct S',
            'Graphene Laser MP Racquet': 'Graphene Laser MP Racquet',
            'Graphene Laser OS Racquet': 'Graphene Laser OS Racquet',
            'Graphene Prestige Midplus': 'Graphene Prestige Midplus',
            'Graphene Prestige Pro': 'Graphene Prestige Pro',
            'Graphene Prestige PWR': 'Graphene Prestige PWR',
            'Graphene Prestige Rev Pro': 'Graphene Prestige Rev Pro',
            'Graphene Prestige S': 'Graphene Prestige S',
            'Graphene Radical Midplus': 'Graphene Radical Midplus',
            'Graphene Radical Pro': 'Graphene Radical Pro',
            'Graphene Radical Rev': 'Graphene Radical Rev',
            'Graphene Radical S': 'Graphene Radical S',
            'Graphene Speed MP': 'Graphene Speed MP',
            'Graphene Speed Pro': 'Graphene Speed Pro',
            'Graphene Speed PWR': 'Graphene Speed PWR',
            'Graphene Speed Rev': 'Graphene Speed Rev',
            'Graphene Speed S': 'Graphene Speed S',
            'Graphene Touch Extreme Lite': 'Graphene Touch Extreme Lite',
            'Graphene Touch Extreme MP': 'Graphene Touch Extreme MP',
            'Graphene Touch Instinct Adaptive': 'Graphene Touch Instinct Adaptive',
            'Graphene Touch Instinct Lite': 'Graphene Touch Instinct Lite',
            'Graphene Touch Instinct MP': 'Graphene Touch Instinct MP',
            'Graphene Touch Instinct PWR': 'Graphene Touch Instinct PWR',
            'Graphene Touch Instinct S': 'Graphene Touch Instinct S',
            'Graphene Touch Prestige Mid': 'Graphene Touch Prestige Mid',
            'Graphene Touch Prestige Midplus': 'Graphene Touch Prestige Midplus',
            'Graphene Touch Prestige Midplus (': 'Graphene Touch Prestige Midplus (',
            'Graphene Touch Prestige Pro': 'Graphene Touch Prestige Pro',
            'Graphene Touch Prestige Tour': 'Graphene Touch Prestige Tour',
            'Graphene Touch Radical MP': 'Graphene Touch Radical MP',
            'Graphene Touch Radical MP Ltd.': 'Graphene Touch Radical MP Ltd.',
            'Graphene Touch Radical Pro': 'Graphene Touch Radical Pro',
            'Graphene Touch Radical PWR': 'Graphene Touch Radical PWR',
            'Graphene Touch Radical S': 'Graphene Touch Radical S',
            'Graphene Touch Speed Adaptive': 'Graphene Touch Speed Adaptive',
            'Graphene Touch Speed MP': 'Graphene Touch Speed MP',
            'Graphene Touch Speed Pro': 'Graphene Touch Speed Pro',
            'Graphene Touch Speed PWR': 'Graphene Touch Speed PWR',
            'Graphene Touch Speed S': 'Graphene Touch Speed S',
            'Graphene XT Extreme Lite': 'Graphene XT Extreme Lite',
            'Graphene XT Extreme MP A': 'Graphene XT Extreme MP A',
            'Graphene XT Extreme Pro': 'Graphene XT Extreme Pro',
            'Graphene XT Instinct MP': 'Graphene XT Instinct MP',
            'Graphene XT Instinct PWR': 'Graphene XT Instinct PWR',
            'Graphene XT Instinct Rev Pro': 'Graphene XT Instinct Rev Pro',
            'Graphene XT Instinct S': 'Graphene XT Instinct S',
            'Graphene XT Prestige Midplus': 'Graphene XT Prestige Midplus',
            'Graphene XT Prestige Pro': 'Graphene XT Prestige Pro',
            'Graphene XT Prestige PWR': 'Graphene XT Prestige PWR',
            'Graphene XT Prestige Rev Pro': 'Graphene XT Prestige Rev Pro',
            'Graphene XT Prestige S': 'Graphene XT Prestige S',
            'Graphene XT Radical Lite': 'Graphene XT Radical Lite',
            'Graphene XT Radical MP': 'Graphene XT Radical MP',
            'Graphene XT Radical MP A': 'Graphene XT Radical MP A',
            'Graphene XT Radical Pro': 'Graphene XT Radical Pro',
            'Graphene XT Radical PWR': 'Graphene XT Radical PWR',
            'Graphene XT Radical S': 'Graphene XT Radical S',
            'Graphene XT Speed Lite': 'Graphene XT Speed Lite',
            'Graphene XT Speed MP': 'Graphene XT Speed MP',
            'Graphene XT Speed MP A': 'Graphene XT Speed MP A',
            'Graphene XT Speed Pro': 'Graphene XT Speed Pro',
            'Graphene XT Speed PWR': 'Graphene XT Speed PWR',
            'Graphene XT Speed Rev Pro': 'Graphene XT Speed Rev Pro',
            'Graphene XT Speed S': 'Graphene XT Speed S',
            'Gravity Lite 2021': 'Gravity Lite 2021',
            'Gravity MP 2021': 'Gravity MP 2021',
            'Gravity Pro 2021': 'Gravity Pro 2021',
            'Gravity S 2021': 'Gravity S 2021',
            'Gravity Tour 2021': 'Gravity Tour 2021',
            'Hornet ES 100': 'Hornet ES 100',
            'Hornet ES 110': 'Hornet ES 110',
            'Ionic Ki 15 260': 'Ionic Ki 15 260',
            'Ionic Ki 5 315': 'Ionic Ki 5 315',
            'Juice 100': 'Juice 100',
            'Juice 100L': 'Juice 100L',
            'Juice 100S': 'Juice 100S',
            'Juice 100UL': 'Juice 100UL',
            'Juice 108': 'Juice 108',
            'K Six One 95 (18x20)': 'K Six One 95 (18x20)',
            'Ki 10': 'Ki 10',
            'Ki 10 (305)': 'Ki 10 (305)',
            'Ki 15 (300)': 'Ki 15 (300)',
            'Ki 15 260': 'Ki 15 260',
            'Ki 30': 'Ki 30',
            'Ki 5 (280)': 'Ki 5 (280)',
            'Ki 5 (300)': 'Ki 5 (300)',
            'Ki 5 (320)': 'Ki 5 (320)',
            'Ki Black Ace Pro': 'Ki Black Ace Pro',
            'Ki Q Tour (300)': 'Ki Q Tour (300)',
            'Ki Q+ 15 (2019)': 'Ki Q+ 15 (2019)',
            'Ki Q+ 15 (285)': 'Ki Q+ 15 (285)',
            'Ki Q+ 15 Light (2019)': 'Ki Q+ 15 Light (2019)',
            'Ki Q+ 15 Light (260g)': 'Ki Q+ 15 Light (260g)',
            'Ki Q+ 15 Pro': 'Ki Q+ 15 Pro',
            'Ki Q+ 20': 'Ki Q+ 20',
            'Ki Q+ 30 (2019)': 'Ki Q+ 30 (2019)',
            'Ki Q+ 30 (260)': 'Ki Q+ 30 (260)',
            'Ki Q+ 5 (2019)': 'Ki Q+ 5 (2019)',
            'Ki Q+ 5 (290)': 'Ki Q+ 5 (290)',
            'Ki Q+ 5 Pro (2019)': 'Ki Q+ 5 Pro (2019)',
            'Ki Q+ 5 Pro (310)': 'Ki Q+ 5 Pro (310)',
            'Ki Q+ 5X Pro (2019)': 'Ki Q+ 5X Pro (2019)',
            'Ki Q+ 5X Pro (310)': 'Ki Q+ 5X Pro (310)',
            'Ki Q+ Tour (2019)': 'Ki Q+ Tour (2019)',
            'Ki Q+ Tour (300)': 'Ki Q+ Tour (300)',
            'Ki Q+ Tour Pro (315) (2019)': 'Ki Q+ Tour Pro (315) (2019)',
            'Ki Q+ Tour Pro (325)': 'Ki Q+ Tour Pro (325)',
            'Ki Q+ Tour Pro (325) (2019)': 'Ki Q+ Tour Pro (325) (2019)',
            'Ki Q+ Tour Pro 315': 'Ki Q+ Tour Pro 315',
            'Ki Q+15 (285)': 'Ki Q+15 (285)',
            'Ki Q+15 Light (260g)': 'Ki Q+15 Light (260g)',
            'Ki Q+30 (260)': 'Ki Q+30 (260)',
            'Ki Q+5 (290)': 'Ki Q+5 (290)',
            'Ki Q+5 Pro (310)': 'Ki Q+5 Pro (310)',
            'Ki Q+5X Pro (310)': 'Ki Q+5X Pro (310)',
            'Ki Q+Tour (300)': 'Ki Q+Tour (300)',
            'Ki Q+Tour Pro (325)': 'Ki Q+Tour Pro (325)',
            'Ki Q15 (260)': 'Ki Q15 (260)',
            'Ki Q15 (280)': 'Ki Q15 (280)',
            'Ki Q15 (310)': 'Ki Q15 (310)',
            'Ki Q30 (260)': 'Ki Q30 (260)',
            'Ki QTour': 'Ki QTour',
            'Kinetic Ki Q5 (295g)': 'Kinetic Ki Q5 (295g)',
            'Kinetic Ki Q5 (315g)': 'Kinetic Ki Q5 (315g)',
            'Kinetic Ki Q5X': 'Kinetic Ki Q5X',
            'Kinetic Q5 (295g)': 'Kinetic Q5 (295g)',
            'Kinetic Q5 (315) 2013': 'Kinetic Q5 (315) 2013',
            'Kinetic Q5 (315g)': 'Kinetic Q5 (315g)',
            'Kinetic Q5 X': 'Kinetic Q5 X',
            'Legacy 120': 'Legacy 120',
            'Lightning 100': 'Lightning 100',
            'Lightning 105': 'Lightning 105',
            'Lightning 110': 'Lightning 110',
            'MXG 1': 'MXG 1',
            'MXG 3': 'MXG 3',
            'MXG 5': 'MXG 5',
            'MXG 7': 'MXG 7',
            'O3 Blue LS': 'O3 Blue LS',
            'O3 Legacy 105': 'O3 Legacy 105',
            'O3 Legacy 110': 'O3 Legacy 110',
            'O3 Legacy 120': 'O3 Legacy 120',
            'O3 Red LS': 'O3 Red LS',
            'O3 White LS': 'O3 White LS',
            'Organix 1': 'Organix 1',
            'Organix 10 (295g)': 'Organix 10 (295g)',
            'Organix 10 (325g)': 'Organix 10 (325g)',
            'Organix 10 Mid': 'Organix 10 Mid',
            'Organix 3': 'Organix 3',
            'Organix 5': 'Organix 5',
            'Organix 7 (295g)': 'Organix 7 (295g)',
            'Organix 7 (310g)': 'Organix 7 (310g)',
            'Organix 9': 'Organix 9',
            'Organix V1 Midplus': 'Organix V1 Midplus',
            'Organix V1 Oversize': 'Organix V1 Oversize',
            'Organix V1 Pro': 'Organix V1 Pro',
            'Original Graphite 107': 'Original Graphite 107',
            'Phantom 100': 'Phantom 100',
            'Phantom Pro 100': 'Phantom Pro 100',
            'Phantom Pro 100P': 'Phantom Pro 100P',
            'Phantom Pro 93P': 'Phantom Pro 93P',
            'Power Bridge 10 (2013) Mid': 'Power Bridge 10 (2013) Mid',
            'Power Bridge 10 Mid': 'Power Bridge 10 Mid',
            'Precision 100': 'Precision 100',
            'Precision 100 Tour': 'Precision 100 Tour',
            'Precision 98': 'Precision 98',
            'Precision 98 Tour': 'Precision 98 Tour',
            'Premier 105 ESP': 'Premier 105 ESP',
            'Premier 105L ESP': 'Premier 105L ESP',
            'Premier 115 ESP': 'Premier 115 ESP',
            'Premier 115L ESP': 'Premier 115L ESP',
            'Pro 10': 'Pro 10',
            'Pro 8': 'Pro 8',
            'Pro One 97': 'Pro One 97',
            'Pro Open 100': 'Pro Open 100',
            'Pro Staff 100L': 'Pro Staff 100L',
            'Pro Staff 100L BLX': 'Pro Staff 100L BLX',
            'Pro Staff 100LS': 'Pro Staff 100LS',
            'Pro Staff 6.0 85': 'Pro Staff 6.0 85',
            'Pro Staff 90': 'Pro Staff 90',
            'Pro Staff 95': 'Pro Staff 95',
            'Pro Staff 95S': 'Pro Staff 95S',
            'Pro Staff 97': 'Pro Staff 97',
            'Pro Staff 97 Countervail': 'Pro Staff 97 Countervail',
            'Pro Staff 97 Countervail Black': 'Pro Staff 97 Countervail Black',
            'Pro Staff 97 LS': 'Pro Staff 97 LS',
            'Pro Staff 97 ULS': 'Pro Staff 97 ULS',
            'Pro Staff 97 v13': 'Pro Staff 97 v13',
            'Pro Staff 97L': 'Pro Staff 97L',
            'Pro Staff 97L Countervail Black': 'Pro Staff 97L Countervail Black',
            'Pro Staff 97L v13': 'Pro Staff 97L v13',
            'Pro Staff 97S': 'Pro Staff 97S',
            'Pro Staff 97UL v13': 'Pro Staff 97UL v13',
            'Pro Staff RF 85 Ltd. Edition': 'Pro Staff RF 85 Ltd. Edition',
            'Pro Staff RF97 Autograph': 'Pro Staff RF97 Autograph',
            'Pro Staff RF97 Autograph 2018': 'Pro Staff RF97 Autograph 2018',
            'Pro Staff RF97 Autograph Black': 'Pro Staff RF97 Autograph Black',
            'Pro Staff RF97 v13': 'Pro Staff RF97 v13',
            'Pro Tour 2.0': 'Pro Tour 2.0',
            'Protocol 285': 'Protocol 285',
            'Protocol 300': 'Protocol 300',
            'Protocol 325': 'Protocol 325',
            'Pure Aero': 'Pure Aero',
            'Pure Aero 2019': 'Pure Aero 2019',
            'Pure Aero Lite': 'Pure Aero Lite',
            'Pure Aero Lite 2019': 'Pure Aero Lite 2019',
            'Pure Aero Play': 'Pure Aero Play',
            'Pure Aero Plus': 'Pure Aero Plus',
            'Pure Aero Plus 2019': 'Pure Aero Plus 2019',
            'Pure Aero Rafa': 'Pure Aero Rafa',
            'Pure Aero Team': 'Pure Aero Team',
            'Pure Aero Team 2019': 'Pure Aero Team 2019',
            'Pure Aero Tour': 'Pure Aero Tour',
            'Pure Aero Tour 2019': 'Pure Aero Tour 2019',
            'Pure Aero VS': 'Pure Aero VS',
            'Pure Aero VS Stars & Stripes': 'Pure Aero VS Stars & Stripes',
            'Pure Aero VS Tour': 'Pure Aero VS Tour',
            'Pure Control': 'Pure Control',
            'Pure Control 95': 'Pure Control 95',
            'Pure Control 95 Plus': 'Pure Control 95 Plus',
            'Pure Control Tour': 'Pure Control Tour',
            'Pure Control Tour Plus': 'Pure Control Tour Plus',
            'Pure Drive 107 2012': 'Pure Drive 107 2012',
            'Pure Drive 107 2015': 'Pure Drive 107 2015',
            'Pure Drive 107 2018': 'Pure Drive 107 2018',
            'Pure Drive 107 2021': 'Pure Drive 107 2021',
            'Pure Drive 110 2015': 'Pure Drive 110 2015',
            'Pure Drive 110 2018': 'Pure Drive 110 2018',
            'Pure Drive 110 2021': 'Pure Drive 110 2021',
            'Pure Drive 2012': 'Pure Drive 2012',
            'Pure Drive 2015': 'Pure Drive 2015',
            'Pure Drive 2018': 'Pure Drive 2018',
            'Pure Drive 2021': 'Pure Drive 2021',
            'Pure Drive Lite 2012': 'Pure Drive Lite 2012',
            'Pure Drive Lite 2015': 'Pure Drive Lite 2015',
            'Pure Drive Lite 2018': 'Pure Drive Lite 2018',
            'Pure Drive Lite 2021': 'Pure Drive Lite 2021',
            'Pure Drive Plus 2012': 'Pure Drive Plus 2012',
            'Pure Drive Plus 2015': 'Pure Drive Plus 2015',
            'Pure Drive Plus 2018': 'Pure Drive Plus 2018',
            'Pure Drive Plus 2021': 'Pure Drive Plus 2021',
            'Pure Drive Roddick 2009': 'Pure Drive Roddick 2009',
            'Pure Drive Roddick 2012': 'Pure Drive Roddick 2012',
            'Pure Drive Roddick Plus 2009': 'Pure Drive Roddick Plus 2009',
            'Pure Drive Roddick Plus 2012': 'Pure Drive Roddick Plus 2012',
            'Pure Drive Team 2015': 'Pure Drive Team 2015',
            'Pure Drive Team 2018': 'Pure Drive Team 2018',
            'Pure Drive Team 2021': 'Pure Drive Team 2021',
            'Pure Drive Tour 2015': 'Pure Drive Tour 2015',
            'Pure Drive Tour 2018': 'Pure Drive Tour 2018',
            'Pure Drive Tour 2021': 'Pure Drive Tour 2021',
            'Pure Drive Tour Plus 2015': 'Pure Drive Tour Plus 2015',
            'Pure Drive Tour Plus 2018': 'Pure Drive Tour Plus 2018',
            'Pure Drive VS': 'Pure Drive VS',
            'Pure Strike 100': 'Pure Strike 100',
            'Pure Strike 100 3rd Gen': 'Pure Strike 100 3rd Gen',
            'Pure Strike 16x19': 'Pure Strike 16x19',
            'Pure Strike 16x19 (Project One7)': 'Pure Strike 16x19 (Project One7)',
            'Pure Strike 16x19 3rd Gen': 'Pure Strike 16x19 3rd Gen',
            'Pure Strike 18x20': 'Pure Strike 18x20',
            'Pure Strike 18x20 3rd Gen': 'Pure Strike 18x20 3rd Gen',
            'Pure Strike 98 16x19 (Project One': 'Pure Strike 98 16x19 (Project One',
            'Pure Strike 98 18x20': 'Pure Strike 98 18x20',
            'Pure Strike Team': 'Pure Strike Team',
            'Pure Strike Team 3rd Gen': 'Pure Strike Team 3rd Gen',
            'Pure Strike Tour': 'Pure Strike Tour',
            'Pure Strike Tour 3rd Gen': 'Pure Strike Tour 3rd Gen',
            'Pure Strike VS': 'Pure Strike VS',
            'Pure Strike VS Tour': 'Pure Strike VS Tour',
            'Q Tour (300)': 'Q Tour (300)',
            'Q Tour 2013': 'Q Tour 2013',
            'Q15': 'Q15',
            'Q15 (260)': 'Q15 (260)',
            'Q15 (280)': 'Q15 (280)',
            'Q15 (310)': 'Q15 (310)',
            'Q30': 'Q30',
            'Q5 (295)': 'Q5 (295)',
            'Q5 (315)': 'Q5 (315)',
            'Q5 X': 'Q5 X',
            'Q5 X 2013': 'Q5 X 2013',
            'QTour 295': 'QTour 295',
            'Radical MP 2021': 'Radical MP 2021',
            'Radical Pro 2021': 'Radical Pro 2021',
            'Radical S 2021': 'Radical S 2021',
            'Rebel 98 ESP': 'Rebel 98 ESP',
            'REGNA 100': 'REGNA 100',
            'Response 97': 'Response 97',
            'Ripstick 100 280g': 'Ripstick 100 280g',
            'Ripstick 100 300g': 'Ripstick 100 300g',
            'Six One Team 95 (2012)': 'Six One Team 95 (2012)',
            'Six.One 95 (16x18)': 'Six.One 95 (16x18)',
            'Six.One 95 (18x20)': 'Six.One 95 (18x20)',
            'Six.One 95 BLX (16x18)': 'Six.One 95 BLX (16x18)',
            'Six.One 95 BLX (18x20)': 'Six.One 95 BLX (18x20)',
            'Six.One 95L': 'Six.One 95L',
            'Six.One 95S': 'Six.One 95S',
            'Six.One Team 95': 'Six.One Team 95',
            'Srixon CS 10.0': 'Srixon CS 10.0',
            'Srixon CS 8.0': 'Srixon CS 8.0',
            'Srixon CX 200': 'Srixon CX 200',
            'Srixon CX 200 LS': 'Srixon CX 200 LS',
            'Srixon CX 200 Tour 16x19': 'Srixon CX 200 Tour 16x19',
            'Srixon CX 200 Tour 18x20': 'Srixon CX 200 Tour 18x20',
            'Srixon CX 200+': 'Srixon CX 200+',
            'Srixon CX 400': 'Srixon CX 400',
            'Srixon Revo CV 3.0': 'Srixon Revo CV 3.0',
            'Srixon Revo CV 3.0 F': 'Srixon Revo CV 3.0 F',
            'Srixon Revo CV 3.0 F LS': 'Srixon Revo CV 3.0 F LS',
            'Srixon Revo CV 3.0 F Tour': 'Srixon Revo CV 3.0 F Tour',
            'Srixon Revo CV 5.0': 'Srixon Revo CV 5.0',
            'Srixon Revo CV 5.0 OS': 'Srixon Revo CV 5.0 OS',
            'Srixon Revo CX 2.0': 'Srixon Revo CX 2.0',
            'Srixon Revo CX 2.0 LS': 'Srixon Revo CX 2.0 LS',
            'Srixon Revo CX 2.0 Tour 18x20': 'Srixon Revo CX 2.0 Tour 18x20',
            'Srixon Revo CX 4.0': 'Srixon Revo CX 4.0',
            'Srixon Revo CZ 100S': 'Srixon Revo CZ 100S',
            'Srixon Revo CZ 98D': 'Srixon Revo CZ 98D',
            'Steam 105S': 'Steam 105S',
            'Steam 96': 'Steam 96',
            'Steam 99': 'Steam 99',
            'Steam 99LS': 'Steam 99LS',
            'Steam 99S': 'Steam 99S',
            'Strike G': 'Strike G',
            'Super G 1': 'Super G 1',
            'Super G 10 (295g)': 'Super G 10 (295g)',
            'Super G 10 (325g)': 'Super G 10 (325g)',
            'Super G 10 Mid 320': 'Super G 10 Mid 320',
            'Super G 10 Mid 330': 'Super G 10 Mid 330',
            'Super G 2': 'Super G 2',
            'Super G 3': 'Super G 3',
            'Super G 4': 'Super G 4',
            'Super G 5': 'Super G 5',
            'Super G 6': 'Super G 6',
            'Super G 7': 'Super G 7',
            'Super G 7 295G': 'Super G 7 295G',
            'Super G 8 (300g)': 'Super G 8 (300g)',
            'Super G 8 (315g)': 'Super G 8 (315g)',
            'Super G 9': 'Super G 9',
            'Super G V1 Midplus': 'Super G V1 Midplus',
            'Super G V1 Oversize': 'Super G V1 Oversize',
            'Super G V1 Pro': 'Super G V1 Pro',
            'Surge 100 BLX': 'Surge 100 BLX',
            'SX 600': 'SX 600',
            'Synergy 98': 'Synergy 98',
            'T. Rebound Tempo 290': 'T. Rebound Tempo 290',
            'Team Speed Blue': 'Team Speed Blue',
            'Team Speed Red': 'Team Speed Red',
            'Textreme Beast 100': 'Textreme Beast 100',
            'Textreme Beast 100L': 'Textreme Beast 100L',
            'Textreme Beast Pro 100 LB': 'Textreme Beast Pro 100 LB',
            'Textreme Beast Pro 100 Longbody': 'Textreme Beast Pro 100 Longbody',
            'Textreme Premier 105': 'Textreme Premier 105',
            'Textreme Premier 120': 'Textreme Premier 120',
            'Textreme Tour 100L': 'Textreme Tour 100L',
            'Textreme Tour 100P': 'Textreme Tour 100P',
            'Textreme Tour 100T': 'Textreme Tour 100T',
            'Textreme Tour 95': 'Textreme Tour 95',
            'Textreme Warrior 100': 'Textreme Warrior 100',
            'Textreme Warrior 100L': 'Textreme Warrior 100L',
            'Textreme Warrior 100T': 'Textreme Warrior 100T',
            'Textreme Warrior 107': 'Textreme Warrior 107',
            'Textreme Warrior 107T': 'Textreme Warrior 107T',
            'TF40 305': 'TF40 305',
            'TF40 315': 'TF40 315',
            'TFight 255': 'TFight 255',
            'TFight 295 Dynacore': 'TFight 295 Dynacore',
            'TFight 295 MP': 'TFight 295 MP',
            'TFight 295 RS': 'TFight 295 RS',
            'TFight 295 TP ATP': 'TFight 295 TP ATP',
            'TFight 300 Dynacore': 'TFight 300 Dynacore',
            'TFight 300 RS': 'TFight 300 RS',
            'TFight 305 Dynacore': 'TFight 305 Dynacore',
            'TFight 305 RS': 'TFight 305 RS',
            'TFight 305 TP ATP': 'TFight 305 TP ATP',
            'TFight 315 Dynacore': 'TFight 315 Dynacore',
            'TFight 315 Ltd. TP ATP 16 Main': 'TFight 315 Ltd. TP ATP 16 Main',
            'TFight 315 Ltd. TP ATP 18 Main': 'TFight 315 Ltd. TP ATP 18 Main',
            'TFight 315 RS': 'TFight 315 RS',
            'TFight 320 TP ATP': 'TFight 320 TP ATP',
            'TFight 325 Dynacore': 'TFight 325 Dynacore',
            'TFight 325 TP ATP': 'TFight 325 TP ATP',
            'TFight DC 300': 'TFight DC 300',
            'TFight DC 305': 'TFight DC 305',
            'TFight DC 315': 'TFight DC 315',
            'TFight DC 320': 'TFight DC 320',
            'TFight DC 320': 'TFight DC 320',
            'TFlash 270 CES': 'TFlash 270 CES',
            'TFlash 270 PS': 'TFlash 270 PS',
            'TFlash 285 CES': 'TFlash 285 CES',
            'TFlash 285 PS': 'TFlash 285 PS',
            'TFlash 300 ATP': 'TFlash 300 ATP',
            'TFlash 300 CES': 'TFlash 300 CES',
            'TFlash 300 Dynacore ATP': 'TFlash 300 Dynacore ATP',
            'TFlash 300 PS': 'TFlash 300 PS',
            'TFlash 315 ATP': 'TFlash 315 ATP',
            'TFlash 315 Dynacore ATP': 'TFlash 315 Dynacore ATP',
            'Thunder Bolt 110 ESP': 'Thunder Bolt 110 ESP',
            'Thunder Extreme 110 ESP': 'Thunder Extreme 110 ESP',
            'Thunder Strike 100 ESP': 'Thunder Strike 100 ESP',
            'Titanium Ti.S2': 'Titanium Ti.S2',
            'Titanium Ti.S5': 'Titanium Ti.S5',
            'Titanium Ti.S6': 'Titanium Ti.S6',
            'Tour 100 (16x18)': 'Tour 100 (16x18)',
            'Tour 100 (18x20)': 'Tour 100 (18x20)',
            'Tour 100T': 'Tour 100T',
            'Tour 100T ESP': 'Tour 100T ESP',
            'Tour 95': 'Tour 95',
            'Tour 98': 'Tour 98',
            'Tour 98 ESP': 'Tour 98 ESP',
            'Tour Pro 100': 'Tour Pro 100',
            'Tour Pro 100 ESP': 'Tour Pro 100 ESP',
            'Tour Pro 98': 'Tour Pro 98',
            'TRebound 265 Pro': 'TRebound 265 Pro',
            'TRebound 295 Pro': 'TRebound 295 Pro',
            'TRebound 298 IGA': 'TRebound 298 IGA',
            'Twistpower X100 Racquets': 'Twistpower X100 Racquets',
            'Twistpower X97 Tour': 'Twistpower X97 Tour',
            'Two BLX': 'Two BLX',
            'Two BLX 2014': 'Two BLX 2014',
            'Ultra 100': 'Ultra 100',
            'Ultra 100 Countervail': 'Ultra 100 Countervail',
            'Ultra 100 v3': 'Ultra 100 v3',
            'Ultra 100L': 'Ultra 100L',
            'Ultra 100L v3': 'Ultra 100L v3',
            'Ultra 100UL': 'Ultra 100UL',
            'Ultra 100UL v3': 'Ultra 100UL v3',
            'Ultra 103S': 'Ultra 103S',
            'Ultra 105S Countervail': 'Ultra 105S Countervail',
            'Ultra 108': 'Ultra 108',
            'Ultra 108 v3': 'Ultra 108 v3',
            'Ultra 110': 'Ultra 110',
            'Ultra 97': 'Ultra 97',
            'Ultra Tour': 'Ultra Tour',
            'Ultra XP 100LS': 'Ultra XP 100LS',
            'Ultra XP 100S': 'Ultra XP 100S',
            'Ultra XP 110S': 'Ultra XP 110S',
            'V-Cell 10 300g': 'V-Cell 10 300g',
            'V-Cell 10 320g': 'V-Cell 10 320g',
            'V-Cell 2': 'V-Cell 2',
            'V-Cell 4': 'V-Cell 4',
            'V-Cell 6': 'V-Cell 6',
            'V-Cell 8 285g': 'V-Cell 8 285g',
            'V-Cell 8 300g': 'V-Cell 8 300g',
            'V-Cell 8 315g': 'V-Cell 8 315g',
            'V-Cell 9': 'V-Cell 9',
            'V-Con 17 OS': 'V-Con 17 OS',
            'VCORE 100': 'VCORE 100',
            'VCORE 100 (280)': 'VCORE 100 (280)',
            'VCORE 100 (300)': 'VCORE 100 (300)',
            'VCORE 100+': 'VCORE 100+',
            'VCORE 100L': 'VCORE 100L',
            'VCORE 95': 'VCORE 95',
            'VCORE 95 Red': 'VCORE 95 Red',
            'VCORE 98': 'VCORE 98',
            'VCORE 98 (285)': 'VCORE 98 (285)',
            'VCORE 98 (285) Red': 'VCORE 98 (285) Red',
            'VCORE 98 (305)': 'VCORE 98 (305)',
            'VCORE 98+': 'VCORE 98+',
            'VCORE 98L': 'VCORE 98L',
            'VCORE Ace': 'VCORE Ace',
            'VCORE Duel G 100': 'VCORE Duel G 100',
            'VCORE Duel G 100 (300g)': 'VCORE Duel G 100 (300g)',
            'VCORE Duel G 100 Lite': 'VCORE Duel G 100 Lite',
            'VCORE Duel G 97 (310g)': 'VCORE Duel G 97 (310g)',
            'VCORE Duel G 97 (330g)': 'VCORE Duel G 97 (330g)',
            'VCORE Duel G 97 (330g) (Wawrinka)': 'VCORE Duel G 97 (330g) (Wawrinka)',
            'VCORE Feel': 'VCORE Feel',
            'VCORE Pro 100 (280)': 'VCORE Pro 100 (280)',
            'VCORE Pro 100 (300)': 'VCORE Pro 100 (300)',
            'VCORE Pro 97 (290)': 'VCORE Pro 97 (290)',
            'VCORE Pro 97 (310)': 'VCORE Pro 97 (310)',
            'VCORE Pro 97 (330)': 'VCORE Pro 97 (330)',
            'VCORE Pro 97HD 18x20': 'VCORE Pro 97HD 18x20',
            'VCORE Si 100': 'VCORE Si 100',
            'VCORE Si 100 Lite': 'VCORE Si 100 Lite',
            'VCORE Si 105': 'VCORE Si 105',
            'VCORE Si 98': 'VCORE Si 98',
            'VCORE Si 98 Lite': 'VCORE Si 98 Lite',
            'VCORE Si Team': 'VCORE Si Team',
            'VCORE SV 100': 'VCORE SV 100',
            'VCORE SV 100 Lite': 'VCORE SV 100 Lite',
            'VCORE SV 100+': 'VCORE SV 100+',
            'VCORE SV 100S': 'VCORE SV 100S',
            'VCORE SV 95': 'VCORE SV 95',
            'VCORE SV 98': 'VCORE SV 98',
            'VCORE SV 98 Lite': 'VCORE SV 98 Lite',
            'VCORE SV 98+': 'VCORE SV 98+',
            'VCORE Team': 'VCORE Team',
            'VCORE Tour 89': 'VCORE Tour 89',
            'VCORE Tour 97 (310g)': 'VCORE Tour 97 (310g)',
            'VCORE Tour 97 (330g)': 'VCORE Tour 97 (330g)',
            'VCORE Tour F 93': 'VCORE Tour F 93',
            'VCORE Tour F 97 (290g)': 'VCORE Tour F 97 (290g)',
            'VCORE Tour F 97 (310g)': 'VCORE Tour F 97 (310g)',
            'VCORE Tour G 310': 'VCORE Tour G 310',
            'VCORE Tour HG 330 (Wawrinka)': 'VCORE Tour HG 330 (Wawrinka)',
            'VCORE Xi 100': 'VCORE Xi 100',
            'VCORE Xi 100 Lite': 'VCORE Xi 100 Lite',
            'VCORE Xi 98': 'VCORE Xi 98',
            'VCORE Xi Team': 'VCORE Xi Team',
            'VCORE Xi Team Plus': 'VCORE Xi Team Plus',
            'V-Feel 1': 'V-Feel 1',
            'V-Feel 10 (300)': 'V-Feel 10 (300)',
            'V-Feel 10 (300g)': 'V-Feel 10 (300g)',
            'V-Feel 10 (320)': 'V-Feel 10 (320)',
            'V-Feel 10 (320g)': 'V-Feel 10 (320g)',
            'V-Feel 2': 'V-Feel 2',
            'V-Feel 3': 'V-Feel 3',
            'V-Feel 5': 'V-Feel 5',
            'V-Feel 7': 'V-Feel 7',
            'V-Feel V1 MP': 'V-Feel V1 MP',
            'V-Feel V1 OS': 'V-Feel V1 OS',
            'V-Feel V1 Pro': 'V-Feel V1 Pro',
            'V-Feel V8 Pro': 'V-Feel V8 Pro',
            'V-Sense 1': 'V-Sense 1',
            'V-Sense 10 295g': 'V-Sense 10 295g',
            'V-Sense 10 325g': 'V-Sense 10 325g',
            'V-Sense 10 Mid': 'V-Sense 10 Mid',
            'V-Sense 10 Tour': 'V-Sense 10 Tour',
            'V-Sense 2': 'V-Sense 2',
            'V-Sense 3': 'V-Sense 3',
            'V-Sense 4': 'V-Sense 4',
            'V-Sense 5': 'V-Sense 5',
            'V-Sense 6': 'V-Sense 6',
            'V-Sense 7': 'V-Sense 7',
            'V-Sense 8 285g': 'V-Sense 8 285g',
            'V-Sense 8 300g': 'V-Sense 8 300g',
            'V-Sense 8 315g': 'V-Sense 8 315g',
            'V-Sense 9': 'V-Sense 9',
            'V-Sense V1 MP': 'V-Sense V1 MP',
            'V-Sense V1 OS': 'V-Sense V1 OS',
            'V-Sense V1 Pro': 'V-Sense V1 Pro',
            'Warrior 100': 'Warrior 100',
            'Warrior 100 (300g)': 'Warrior 100 (300g)',
            'Warrior 100 ESP': 'Warrior 100 ESP',
            'Warrior 100 Pro': 'Warrior 100 Pro',
            'Warrior 100L ESP': 'Warrior 100L ESP',
            'Warrior 100L ESP': 'Warrior 100L ESP',
            'Warrior 107': 'Warrior 107',
            'Warrior Pro 100': 'Warrior Pro 100',
            'Warrior Pro 100T ESP': 'Warrior Pro 100T ESP',
            'X Fast Pro 100': 'X Fast Pro 100',
            'X Feel Tour': 'X Feel Tour',
            'X Force Pro': 'X Force Pro',
            'X Force Pro 1': 'X Force Pro 1',
            'X Force Pro No. 1': 'X Force Pro No. 1',
            'X Tour 97': 'X Tour 97',
            'X Tour Pro 97': 'X Tour Pro 97',
            'X-Dual Core Gold 94': 'X-Dual Core Gold 94',
            'X-Dual Gold 99': 'X-Dual Gold 99',
            'X-Dual Platinum 94': 'X-Dual Platinum 94',
            'X-P Dual Black 102': 'X-P Dual Black 102',
            'X-P Dual Lite Black 102': 'X-P Dual Lite Black 102',
            'X-P Dual Lite White 102': 'X-P Dual Lite White 102',
            'XP1': 'XP1',
            'YOUTEK IG Extreme MP 2.0': 'YOUTEK IG Extreme MP 2.0',
            'YOUTEK IG Extreme Pro 2.0': 'YOUTEK IG Extreme Pro 2.0',
            'YOUTEK IG Extreme S 2.0': 'YOUTEK IG Extreme S 2.0',
            'YOUTEK IG Prestige Mid': 'YOUTEK IG Prestige Mid',
            'YOUTEK IG Prestige S': 'YOUTEK IG Prestige S',
            'YOUTEK IG Radical S': 'YOUTEK IG Radical S',
            'YOUTEK IG Speed Lite': 'YOUTEK IG Speed Lite',
        }


        img_name = img_names[self.name]
        return f"https://raw.githubusercontent.com/HiImYong/snrPictures/master/{img_name}.jpg"


class RacketDetail(models.Model):
    racket = models.OneToOneField(Racket, related_name='detail', on_delete=models.CASCADE)
    adminReview = models.TextField()
    adminPower = models.FloatField('운영자파워평점', default=0)
    adminSpin = models.FloatField('운영자스핀평점', default=0)
    adminManeuverability = models.FloatField('운영자조작성평점', default=0)
    adminStability = models.FloatField('운영자면안정성평점', default=0)
    adminComfort = models.FloatField('운영자안락함평점', default=0)
    adminAvgScore = models.FloatField('운영자평점평균', default=0)
