# Generated by Django 3.2.9 on 2022-02-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='선수이름')),
                ('birth', models.DateTimeField(default='0000.00.00', verbose_name='생일')),
                ('trunPro', models.IntegerField(default=0, verbose_name='프로전향')),
                ('weight', models.IntegerField(default=0, verbose_name='몸무게')),
                ('height', models.FloatField(default=0, verbose_name='키')),
                ('contury', models.IntegerField(default=0, verbose_name='국가')),
                ('forehand', models.IntegerField(default=0, verbose_name='포핸드위치')),
                ('backhand', models.CharField(default='등록전', max_length=20, verbose_name='백핸드종류')),
                ('racketBrand', models.CharField(default='등록전', max_length=20, verbose_name='선수이름')),
            ],
        ),
    ]
