# Generated by Django 3.2.9 on 2022-02-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='trunPro',
            new_name='turnPro',
        ),
        migrations.RemoveField(
            model_name='player',
            name='contury',
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default='등록전', max_length=20, verbose_name='국가'),
        ),
    ]
