# Generated by Django 3.2.9 on 2022-02-09 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0003_alter_player_forehand'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='like',
            field=models.ManyToManyField(related_name='likePlayer', to=settings.AUTH_USER_MODEL),
        ),
    ]
