# Generated by Django 3.2.9 on 2022-02-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='countLike',
            field=models.IntegerField(default=0, verbose_name='좋아요개수'),
        ),
    ]
