# Generated by Django 3.2.9 on 2022-02-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_playercharacteristic'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercharacteristic',
            name='playerJoin',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='player.player'),
        ),
    ]
