# Generated by Django 3.2.9 on 2022-03-29 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='articleFonignKey',
            new_name='articleForeignKey',
        ),
    ]
