# Generated by Django 3.2.9 on 2022-03-29 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_rename_articlefonignkey_reply_articleforeignkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='subject',
        ),
    ]
