# Generated by Django 3.2.9 on 2022-01-24 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racket', '0002_dummy'),
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorreview',
            name='visitorRacket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitorRacket', to='racket.racket'),
        ),
    ]
